### ISSUE TITLE
Error connecting with SSL

### ISSUE THREAD

**Issue by StevenHenriot** [misugi/zyroom#2]
![Capture](https://user-images.githubusercontent.com/24510899/92327084-7d1b8d00-f057-11ea-862e-2497e9710158.PNG)

API Call Error : Error connecting with SSL. EOF was observed that violates the protocol

**Comment by misugi** [comment]
Hi,
Ok I will try to correct this problem as soon as possible.
Thank you for the info.

Best regards,
Misugi

Le dim. 6 sept. 2020 à 15:44, Steven Henriot <notifications@github.com> a
écrit :

**Comment by StevenHenriot** [comment]
The libeay32 and ssleay32 dlls have been updated.

**Comment by misugi** [comment]
Hi,

New version of zyRoom today 5.1.5 with new DDL files to fix this error.

 

Best regards,

Misugi

 

De : Steven Henriot <notifications@github.com> 
Envoyé : vendredi 18 septembre 2020 10:04
À : misugi/zyroom <zyroom@noreply.github.com>
Cc : misugi <contact@misulud.fr>; Comment <comment@noreply.github.com>
Objet : Re: [misugi/zyroom] Error connecting with SSL (#2)

 

The libeay32 and ssleay32 dlls have been updated.
